version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: aisavdo_backend
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app.db:/app/app.db
    env_file:
      - ./backend/.env
    networks:
      - aisavdo_net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: aisavdo_frontend
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - backend
    networks:
      - aisavdo_net

networks:
  aisavdo_net:
    driver: bridge
